spring:
  batch:
    job:
      enabled: false # disable jobs on startup; triggered by rest
      
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      transaction-id-prefix: ingestion-application
      properties:
        schema.registry.url: http://localhost:18081
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
    template:
      default-topic: persons

  datasource:
    url: jdbc:postgresql://localhost:5432/ingestion
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  flyway:
    enabled: true
    
server:
  port: 8084