spring:
  kafka:
    bootstrap-servers: localhost:19092
    streams:
      application-id: person-stream
      properties:
        schema.registry.url: http://localhost:18081
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
        
server:
  port: 8085